CREATE TABLE USER_ROLES(
id INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(50) ,
  ROLE_NAME VARCHAR(50) ,
  ROLE_DESCRIPTION VARCHAR(100) ,
  ICA VARCHAR(50) ,
  STATUS VARCHAR(10) ,
  CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATED_TIMESTAMP TIMESTAMP
);
